### ISSUE TITLE
Watch with MPV by default?

### ISSUE THREAD

**Issue by BonkaBonka** [antoniy/mpv-youtube-dl-binding#1]
Can you add a preference to have the addon automatically launch mpv when clicking on an mpv link?

My use-case is I have a bunch of .mkv files on a webserver on my lan.  I'd like to be able to simply click on the link and have it open in mpv rather than right-click, scroll to the bottom of the dialog box and then click on the Watch with MPV option.

**Comment by antoniy** [comment]
Hello,

It's kind of specific feature and I don't have much time lately. If you want, you can add it and I'll merge it and publish it for you.

Antoniy
