### ISSUE TITLE
4K streaming

### ISSUE THREAD

**Issue by Poilaucul** [antoniy/mpv-youtube-dl-binding#10]
Hello, I already posted and issue on the youtube-dl issue tracker and it seems that 4K streaming can not be done with it https://github.com/rg3/youtube-dl/issues/6642#issuecomment-133790541 (even though I can perfectly get it to work with MPV with the command below)
>mpv --ytdl-format="bestvideo+bestaudio" https://www.youtube.com/watch?v=q6kIwfEGLO4

Is it possible to forward the parameters to MPV in this fashion to solve this issue?

**Comment by wp9015362** [comment]
> @Poilaucul wrote:
> 
> Is it possible to forward the parameters to MPV in this fashion to solve this issue?

Open Firefox, select the URL bar and in there type:

about:addons

then hit enter, then select "Extensions", then select the "mpv-youtube-dl-binding" extension, then select the "Additional player parameters" field and in there add:

--ytdl-format=bestvideo+bestaudio

:wink:

Or simply use a configuration file:

https://mpv.io/manual/stable/#configuration-files

and put:

ytdl-format=bestvideo+bestaudio

in there :wink:.

Regards

**Comment by Poilaucul** [comment]
I tried that, I don't know if this has been updated since but using "Open
with" Firefox extension instead solved the issue for me.

**Comment by antoniy** [comment]
Considering this plugin only runs mpv for you in the command line, I don't see how 4k streaming is relevant topic. Either mov config file should be used or mpv parameters to achieve what you want. The purpose of the plugin is to interface the native player and run it. Nothing more. I'm glad you've solved your issue.
