### ISSUE TITLE
custom shortcut for context mennu

### ISSUE THREAD

**Issue by dcrystalj** [antoniy/mpv-youtube-dl-binding#11]
I wonder if its possible to make shortcut like this:
I hold alt key (for example) + click  on link and automatically run mpv and prevent default follow the link, so i dont need to right click + mpv

**Comment by antoniy** [comment]
I've check this matter out and could not find a way to make keyboard+mouse combo as a global hotkey that could work as described. Seams useful feature, but I think it just might be outside of browser SDK capabilities for hotkeys.
