### ISSUE TITLE
Mac OS X support?

### ISSUE THREAD

**Issue by 3marcusw** [antoniy/mpv-youtube-dl-binding#14]
it doesn't work on Mac OS X

**Comment by antoniy** [comment]
I honestly don't know if it work on OSX. I see there are 80 active users on Mac OSX so I suppose there is no reason not to work. Have you installed youtube-dl?

**Comment by 3marcusw** [comment]
I have both mpv and youtube-dl installed, and i just confirmed again that it does nothing.

**Comment by mrkapqa** [comment]
Hello , i have tried today on osx Mavericks,

having youtube-dl installed and mpv via macports and also a separate build in the program folder.

it happened with the following location:

/opt/local/bin/mpv


Loading however is slower than on Linux, Windows, it seems.
