### ISSUE TITLE
Doesn't work with vlc in archlinux 64 bit.

### ISSUE THREAD

**Issue by Xenphor** [antoniy/mpv-youtube-dl-binding#15]
I edit the options to use vlc at '/usr/bin/vlc'. When using it, the player opens up, plays video very briefly and then closes.

**Comment by baizon** [comment]
It wont work because the syntax is:
```
mpv "<URL>" ----ytdl-format=best
```
In comparison, if You want to get it work with vlc:
```
youtube-dl "<URL>" -o - | vlc -
```

**Comment by Anon1234** [comment]
Just tested it, works for me. Run firefox from a terminal and watch for an errors (after you run the `Play in MPV command`). Maybe you have some unsupported by VLC options in `Additional player parameters`?

**Comment by Xenphor** [comment]
Weird. I tried it again and it played a video in my home directory instead of what I clicked on in the browser. I don't have any other parameters. I saw the output from the terminal but it's not related because I get the same stuff regardless if it plays or not.

**Comment by Xenphor** [comment]
Using 
youtube-dl "<URL>" -o - | vlc -
Works but I get no video for some reason.

**Comment by Anon1234** [comment]
Try run `vlc "https://www.youtube.com/watch?v=zuQ3Nq2wMyY&index=1&list=PLaiPn4ewcbkHAoPJG88qOnEtscS3VftJz"`, if it wouldn't work there is a problem in your VLC configuration.

**Comment by Xenphor** [comment]
That works.

**Comment by Xenphor** [comment]
Okay using 
`youtube-dl "<URL>" -g - | vlc -`
works

**Comment by Anon1234** [comment]
So what exactly do you get when trying to play video from here https://www.youtube.com/playlist?list=PLaiPn4ewcbkHAoPJG88qOnEtscS3VftJz ?

**Comment by Xenphor** [comment]
Using what command?

**Comment by Anon1234** [comment]
Using ff extension.

**Comment by Xenphor** [comment]
It just plays a local video from my home folder.

**Comment by Anon1234** [comment]
Lol, now i have the same problem.

**Comment by Anon1234** [comment]
Try to add `--` to the `Additional player parameters`.

**Comment by Xenphor** [comment]
Hm that seems to work, thanks.

**Comment by Anon1234** [comment]
np :)
