### ISSUE TITLE
youtube-dl options

### ISSUE THREAD

**Issue by helpdeskdan** [antoniy/mpv-youtube-dl-binding#2]
The ability to add youtube-dl options would be nice.  You've got player parameters, youtube-dl parameters would be great.  Fantastic add on, by the way - 5 stars.

**Comment by antoniy** [comment]
I'm glad it's useful to you and thank you. For MPV there is a way to specify the parameters for youtube-dl but if someone wants to use other player, it might be problematic. I'll think about a way to make it happen but don't have much time lately. May I suggest using youyube-dl ```/etc/youtube-dl.conf``` and/or ```~/.config/youtube-dl/config``` configuration files?

**Comment by helpdeskdan** [comment]
Thanks!
