### ISSUE TITLE
mpv not starting

### ISSUE THREAD

**Issue by tkoehlmann** [antoniy/mpv-youtube-dl-binding#20]
Sorry for the unclear title, but I am not sure what else to name this issue.

I'm running Gentoo 64-bit and I have the following programs (all in $PATH):
* firefox: 38.5
* youtube-dl: 2016.01.27 (but it was also not working with older versions)
* mpv: 0.9.2

So far I have found those things to work just fine from the terminal:
* Downloading a video with youtube-dl 

    `$ youtube-dl https://www.youtube.com/watch?v=lx_vWkv50uk`

* Playing the downloaded video with mpv
* Playing the video directly through mpv

    `$ mpv https://www.youtube.com/watch?v=lx_vWkv50uk`

Yet clicking the button in Firefox does nothing. mpv is located at /usr/bin/mpv (as is the default setting) and I haven't added any other settings in the preferences window.

Any ideas?

**Comment by baizon** [comment]
Have you set your ``` Additional player parameters ``` to this:
```
--ytdl-format=best
```

**Comment by tkoehlmann** [comment]
`mpv https://www.youtube.com/watch?v=lx_vWkv50uk --ytdl-format=best`

Works fine. Setting the additional parameters to `--ytdl-format=best` didn't change anything.

**Comment by tkoehlmann** [comment]
Feel free to close this "issue".

I fiddled around a bit and let the addon call a shell script that I wrote which dumps some stuff into a log file. That's the script here:
`LOG=~/notmpv.log
echo "$*" > $LOG
echo "PATH = $PATH" >> $LOG
mpv $* >> $LOG`

One of the messages I got was `[ytdl_hook] youtube-dl not found, not executable, or broken.` I don't have youtube-dl installed system wide, but in ~/bin, which is added to the $PATH in my .bashrc. When I'm on the terminal the path is fine. For some weird reason it is not when calling the script (and thus also not when pressing the button in Firefox). So the problem is absolutely not in your excellent addon but somewhere either in Firefox, Gnome or whereever.

Regards

**Comment by tkoehlmann** [comment]
In case anyone else has this problem: I figured out what is going on. Apparently GNOME 3 doesn't actually source the rc file of the login shell (not bashrc, not bash_login, not bash_profile).

The PATH needs to be set in ~/.profile for GNOME 3 to actually read and apply it.
