### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by V-J-P** [antoniy/mpv-youtube-dl-binding#25]
If not I'll sign my fork to Mozilla.

**Comment by weedy** [comment]
Please do

**Comment by illumilore** [comment]
Where is the fork?

**Comment by antoniy** [comment]
The project is open source so fork it in a heart beat. :) Personally this was an evening project for me in my frustration with YouTube flash videos. In my mind there is not much useful things to be done further ahead. It was suppose to be a small targeted solution to allow me watch streams with native player with a click of a button. Mission accomplished.

**Comment by polyzen** [comment]
@antoniy, perhaps they mean updating the [extension on AMO](https://addons.mozilla.org/en-us/firefox/addon/watch-with-mpv/)?

Edit: I use a slighlty modified version of [this](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#play-a-link-with-an-external-media-player) with [VimFx](https://github.com/akhodakivskiy/VimFx), which appears to use some of the same code as in your extension. :)
