### ISSUE TITLE
"Not available for your platform" - for FreeBSD

### ISSUE THREAD

**Issue by ivan-83** [antoniy/mpv-youtube-dl-binding#3]
"Not available for your platform" - for FreeBSD at
https://addons.mozilla.org/en-US/firefox/addon/watch-with-mpv/

I'm install manually from here, change path to /usr/local/bin/mpv and all works fine.
Please, fix platform requirements on mozilla addons site.

**Comment by antoniy** [comment]
Thank you for notifying me about this. 

It seams I cannot change the version scope after it has been released. When I publish a new version, I'll scope it for all platforms.

Antoniy
