### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ProinsiasC** [antoniy/mpv-youtube-dl-binding#4]
youtube-dl is still working well but in the past few days this wonderful little add-on does nothing. I'm on an up to date Arch install and can't find anything of relevance in var/log. Happy to give more info but not sure where to start.

**Comment by antoniy** [comment]
I'm on Arch myself and it's working as expected for me. There are some websites that do not work but this is youtube-dl heavy lifting magic. The plugin just executes media player command for you, using the URL from the browser. If you be more specific so I could test it and try to reproduce...?

**Comment by fenque** [comment]
osx 10.10.4, firefox 39, not working

**Comment by ProinsiasC** [comment]
Been updating daily with no change until today, noticed a flash update pending today and it's working again after a pacman -Syu. Only been using it with YouTube and youtube-dl was working fine throughout. Thanks for the prompt reply and sorry about the vaugue report. happy to report all is well again.
The only other thing I can think was now was I'm running mpv-git from AUR which might have got a bit behind....but was still working fine using youtube-dl then mpv to play. Anyways, back on track and thanks for the add-on.
