### ISSUE TITLE
[Request] Support for Pale Moon

### ISSUE THREAD

**Issue by Hund** [antoniy/mpv-youtube-dl-binding#5]
I would like to see support for Pale Moon. :)

**Comment by JamesTheAwesomeDude** [comment]
Seconding this.

**Comment by phikal** [comment]
*Thirding* this too.

**Comment by tumpio** [comment]
You must build it manually with Addon SDK that has support for Pale Moon, or edit the build .xpi file by hand.

**Comment by antoniy** [comment]
I have no expertise on the matter. You could check what @tumpio suggested and see if it works out for you.

**Comment by Hund** [comment]
Where do I download the addon?

**Comment by JamesTheAwesomeDude** [comment]
https://addons.mozilla.org/en-us/firefox/addon/watch-with-mpv/
	~James

**Comment by Hund** [comment]
@JamesTheAwesomeDude And where do I download the addon from there?
