### ISSUE TITLE
[Request] Specify location for youtube-dl

### ISSUE THREAD

**Issue by AsukaLangleyfag** [antoniy/mpv-youtube-dl-binding#7]
I use your addon on windows and it works (tried bomi (mpv-based player) and mpv), but only if you have youtube-dl in the same folder with player. It means you should have as many copies of youtube-dl as players. Also, players often installed in Program Files and users cannot write into it, so to update youtube-dl you have to run it as Administrator or copy it to other location.

**Comment by antoniy** [comment]
I don't know of an option to specify youtube-dl location. I'm not a windows user but have you tried to add youtube-dl (single installation) to your PATH variable and then test it? If you also know of a way to specify youtube-dl location to mpv - let me know.

**Comment by wp9015362** [comment]
Might want to have a look at the following issue:

https://github.com/mpv-player/mpv/issues/2448

This is not an issue for mpv-youtube-dl-binding but rather for mpv directly.

**Comment by wp9015362** [comment]
> @antoniy wrote:
> 
>  If you also know of a way to specify youtube-dl location to mpv - let me know.

Just noticed that it is actually all in the README, see:

https://github.com/rg3/youtube-dl/blob/master/README.md#on-windows-how-should-i-set-up-ffmpeg-and-youtube-dl-where-should-i-put-the-exe-files

Regards

**Comment by antoniy** [comment]
Thank you @wp9015362 for leting everyone know!

Regards
