### ISSUE TITLE
warning if extension doesn't work on site

### ISSUE THREAD

**Issue by beew** [antoniy/mpv-youtube-dl-binding#8]
Hi,

I have been using this wonderful addon for a few months now and it  has been great. However I would like to make a feature request. mpv addon works for a lot of sites but not all, it would be great if there is notification if it encounters a site where it cannot play the video for lacking youtube-dl support. I am asking this because sometimes mpv addon doesn't kick in immediately on sites where it does work, so one has to may be wait a little. It is therefore desirable to have a way to tell users to stop waiting on sites where it doesn't work. 

Thanks a lot for this great addon!

**Comment by antoniy** [comment]
Hello,

I'm glad you enjoy using it. 

I don't know of a way to test initially if a particular link will work with youtube-dl. I don't think they have such feature or at least I could find it. If you have any more info about that, I'll be happy to take a look.

Cheers and take care
