### ISSUE TITLE
Winblows support

### ISSUE THREAD

**Issue by chinatsu-chan** [antoniy/mpv-youtube-dl-binding#9]
Just wondering if this works at all on Windows.

I tried setting the path to file:///C:/Users/Person/mpv.exe - which is my location for mpv but this did not work, nor did lobbing off file:///, C:/, and .exe in various ways.

Nightly 64-bit 42a1 on Windows 7 64-bit.

The default path I saw was for Linux systems but I'm hoping there is some possible support on Windows.

I use binaries provided from http://mpv.srsfckn.biz/

**Comment by dcrystalj** [comment]
I did like this and it works:
C:\\ProgramData\\chocolatey\\lib\\mpv\\tools\\mpv.exe

remember to manually download youtube-dl.exe to tools folder

**Comment by antoniy** [comment]
Thank you for clarifying this, @dcrystalj . I have no windows box to play on but I know for a lot of people who use it successfully on windows.
